module FFI
  module Library
    def attach_gdal_function: (
      _ToS c_function_name,
      Array[Symbol | FFI::Enum | FFI::Type] args,
      ?Symbol | FFI::Enum | FFI::Type ?returns,
      ?blocking: boolish,
      ?convention: :default | :stdcall,
      ?enums: FFI::Enums?,
      ?type_map: ::Hash[String, Symbol]
    ) -> FFI::VariadicInvoker


    def unsupported_gdal_functions: () -> untyped
  end
end
