---
inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Naming/FileName:
  Exclude:
    - lib/ffi-gdal.rb
    - spec/ffi-gdal_spec.rb

Naming/MethodParameterName:
  AllowedNames: [x, y, z]

Style/Documentation:
  Enabled: false

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 2.6
