module FFI
  class MemoryPointer < Pointer
    def self.from_string: (String s) -> FFI::MemoryPointer

    def initialize: (Fixnum | Bignum | Symbol | FFI::Type size, ?Numeric count, ?bool clear) -> instance
  end
end
