module OGR
  class Curve
    include _HasPointer
    include _SpatialReference
    include _ToWkt

    include GDAL::Logger
    include OGR::Geometry::GeometryMethods
    include OGR::Geometry::Length
    include OGR::Geometry::HasTwoCoordinateDimensions

    GEOMETRY_TYPE: :wkbCurve

    def initialize: (FFI::Pointer c_pointer, ?spatial_reference: OGR::SpatialReference?) -> void
  end
end
