module OGR
  class FeatureDefinition
    class AutoPointer < ::FFI::AutoPointer
      extend _AutoPointerRelease
    end

    extend _NewBorrowed[instance]

    def initialize: (OGR::FeatureDefinition::AutoPointer | FFI::Pointer pointer) -> void
  end
end
