module OGR
  class Feature
    include _HasPointer

    def self.create: (OGR::FeatureDefinition feature_definition) -> instance
    def initialize: (FFI::Pointer pointer) -> void
    def clone: -> instance
    def set_from!: (OGR::Feature other_feature, ?be_forgiving: bool) -> void
    def field_count: -> Integer
  end
end
