module OGR
  class FieldDefinition
    class AutoPointer < ::FFI::AutoPointer
      extend _AutoPointerRelease
    end

    extend _NewBorrowed[OGR::FieldDefinition]
    include _HasAutoPointer[OGR::FieldDefinition::AutoPointer]

    def self.field_type_name: (FFI::OGR::Core::ogr_field_type_symbol field_type) -> String
    def self.field_sub_type_name: (FFI::OGR::Core::ogr_field_sub_type_symbol field_sub_type) -> String
    def self.type_sub_type_compatible?: (
      FFI::OGR::Core::ogr_field_type_symbol field_type,
      FFI::OGR::Core::ogr_field_sub_type_symbol field_sub_type
    ) -> bool

    def initialize: (String name) -> void | (FFI::Pointer c_pointer) -> void
    def set: (
      String field_name,
      FFI::OGR::Core::ogr_field_type_symbol field_type,
      ?width: Integer,
      ?precision: Integer,
      ?justification: FFI::OGR::Core::ogr_justification_symbol
    ) -> void

    def name: -> String
    def name=: (String new_name) -> void
    def justification: -> FFI::OGR::Core::ogr_justification_symbol
    def justification=: (FFI::OGR::Core::ogr_justification_symbol new_justification) -> void
    def precision: -> Integer
    def precision=: (Integer new_precision) -> void
    def type: -> FFI::OGR::Core::ogr_field_type_symbol
    def type=: (FFI::OGR::Core::ogr_field_type_symbol new_type) -> void
    def width: -> Integer
    def width=: (Integer new_width) -> void
    def ignored?: -> bool
    def ignored=: (bool new_value) -> void
    def sub_type: -> FFI::OGR::Core::ogr_field_sub_type_symbol
    def sub_type=: (FFI::OGR::Core::ogr_field_sub_type_symbol) -> void
    def default_driver_specific?: -> bool
  end
end
