module OGR
  class Geometry
    include _HasPointer
    include _SpatialReference
    include _ToWkt
    extend OGR::Geometry::ClassMethods
    include GDAL::Logger

    type geometry_class = (
        OGR::Point | OGR::Point25D
        | OGR::LinearRing | OGR::LineString | OGR::LineString25D
        | OGR::Polygon | OGR::Polygon25D
        | OGR::MultiPoint | OGR::MultiPoint25D
        | OGR::MultiLineString | OGR::MultiLineString25D
        | OGR::MultiPolygon | OGR::MultiPolygon25D
        | OGR::GeometryCollection | OGR::GeometryCollection25D
        | OGR::CircularString | OGR::CompoundCurve | OGR::CurvePolygon
        | OGR::MultiCurve | OGR::MultiSurface
        | OGR::Curve | OGR::Surface
        | OGR::NoneGeometry | OGR::UnknownGeometry
    )

    def initialize: (FFI::Pointer geometry_ptr, OGR::SpatialReference ?spatial_reference) -> void
    def empty?: -> bool
    def import_from_wkt: (String wkt_data) -> void
    def type: -> FFI::OGR::Core::wkb_geometry_type_symbol
  end
end
