module OGR
  class LineString25D < OGR::LineString
    include OGR::Geometry::Interfaces::XYZPoints

    GEOMETRY_TYPE: FFI::OGR::Core::wkb_geometry_type_symbol

    def initialize: (?c_pointer: FFI::Pointer?, ?spatial_reference: OGR::SpatialReference?) -> void
  end
end
