module OGR
  class MultiLineString25D < OGR::MultiLineString
    GEOMETRY_TYPE: FFI::OGR::Core::wkb_geometry_type_symbol

    def initialize: (?c_pointer: FFI::Pointer?, ?spatial_reference: OGR::SpatialReference?) -> void
  end
end
