module OGR
  class NoneGeometry
    include _HasAutoPointer[OGR::Geometry::AutoPointer]
    include OGR::Geometry::GeometryMethods

    GEOMETRY_TYPE: :wkbNone

    def initialize: (FFI::Pointer geometry_ptr) -> void
  end
end
