module OGR
  class Point < OGR::Geometry
    include OGR::Geometry::HasTwoCoordinateDimensions

    GEOMETRY_TYPE: :wkbPoint

    def self.new_from_coordinates: (ffi_floatable x, ffi_floatable y) -> void

    def initialize: (?c_pointer: FFI::Pointer?, ?spatial_reference: OGR::SpatialReference?) -> void
    def add_point: (ffi_floatable x, ffi_floatable y) -> void
  end
end
