module OGR
  class StyleTool
    class AutoPointer < ::FFI::AutoPointer
      extend _AutoPointerRelease
    end

    extend _NewBorrowed[instance]
    include _HasPointer

    def initialize: (OGR::StyleTool::AutoPointer | FFI::Pointer pointer) -> void
  end
end
