module OGR
  class StyleTable
    class AutoPointer < ::FFI::AutoPointer
      extend _AutoPointerRelease
    end

    extend _NewBorrowed[OGR::StyleTable]
    include _HasPointer

    def initialize: (OGR::StyleTable::AutoPointer | FFI::Pointer pointer) -> void
  end
end

