module OGR
  class Surface < OGR::Geometry
    include OGR::Geometry::SurfaceMethods
    include OGR::Geometry::HasTwoCoordinateDimensions

    GEOMETRY_TYPE: :wkbSurface

    def initialize: (FFI::Pointer c_pointer, ?spatial_reference: OGR::SpatialReference?) -> void
  end
end
