module GDAL
  module GridAlgorithms
    class MovingAverage
      # @return [FFI::GDAL::GridMovingAverageOptions]
      attr_reader options: untyped

      def initialize: () -> untyped

      # @return [Symbol]
      def c_identifier: () -> :GGA_MovingAverage
    end
  end
end
