module FFI
  module GDAL
    def self.gdal_library_path: -> String
    def self.find_lib: (String lib) -> String
    def self._files_with_constants: -> Array[String]
    def self._file_with_constants: (String file_name) -> String?
    def self.loaded_ffi_libs: -> Array[FFI::DynamicLibrary]

    type version_request_string = "VERSION_NUM" | "RELEASE_DATE" | "RELEASE_NAME" | "--version" | "LICENSE" | "BUILD_INFO"
    def self.GDALVersionInfo: (version_request_string request) -> String
  end
end
