module OGR
  module Geometry
    module Interfaces
      module XYPoints
        include GDAL::Logger

        def x: (Integer point_number) -> Float
        def y: (Integer point_number) -> Float

        def add_point: (Float x, Float y) -> void
        def point: (Integer point_number) -> [Float, Float]
        def set_point: (Integer point_number, Float x, Float y) -> void
        def points: -> Array[Array[Float]]
        def point_count=: (Integer new_count) -> void
        def point_count: -> Integer
      end
    end
  end
end
