module FFI
  module OGR
    module API
      def self.OGR_G_Area: (FFI::Pointer geometry_handle) -> Float
      def self.OGR_G_Length: (FFI::Pointer geometry_handle) -> Float

      def self.OGR_G_GetX: (FFI::Pointer geometry_handle, Integer index) -> Float
      def self.OGR_G_GetY: (FFI::Pointer geometry_handle, Integer index) -> Float
      def self.OGR_G_GetZ: (FFI::Pointer geometry_handle, Integer index) -> Float

      def self.OGR_G_GetPoints: (
        FFI::Pointer geometry_handle,
        FFI::Buffer? x_buffer,
        Integer x_stride,
        FFI::Buffer? y_buffer,
        Integer y_stride,
        FFI::Buffer? z_buffer,
        ?Integer z_stride
      ) -> Integer

      def self.OGR_G_GetPoint: (
        FFI::Pointer geometry_handle,
        Integer index,
        FFI::Buffer x_buffer,
        FFI::Buffer y_buffer,
        FFI::Buffer? z_buffer
      ) -> void

      def self.OGR_G_GetPointCount: (FFI::Pointer geometry_handle) -> Integer
      def self.OGR_G_SetPointCount: (FFI::Pointer geometry_handle, Integer new_point_count) -> void

      def self.OGR_G_AddPoint: (FFI::Pointer geometry_handle, Float x, Float y, Float m) -> void
      def self.OGR_G_AddPoint_2D: (FFI::Pointer geometry_handle, Float x, Float y) -> void

      def self.OGR_G_SetPoint: (FFI::Pointer geometry_handle, Integer vertex_index, Float x, Float y, Float z) -> void
      def self.OGR_G_SetPoint_2D: (FFI::Pointer geometry_handle, Integer vertex_index, Float x, Float y) -> void
    end
  end
end
