class NArray
  BYTE: 1
  SINT: 2
  INT: 3
  LINT: 3
  SFLOAT: 4
  FLOAT: 5
  DFLOAT: 5
  SCOMPLEX: 6
  COMPLEX: 7
  DCOMPLEX: 7
  ROBJ: 8
  NTYPES: 9

  def initialize: (Integer typecode, Integer size, *(String | Integer | Float | Object) values) -> NArray


end
