module OGR
  class Geometry
    module ClassMethods
      def new_from_pointer: (FFI::Pointer geometry_ptr) -> OGR::Geometry::geometry_class
      def create: (FFI::OGR::Core::wkb_geometry_type_symbol geometry_type) -> FFI::Pointer

      def create_from_wkt: (
        String wkt_data,
        ?OGR::SpatialReference ?spatial_ref
      ) -> OGR::Geometry::geometry_class

      def create_from_wkb: (
        String wkb_data,
        ?OGR::SpatialReference ?spatial_ref
      ) -> OGR::Geometry::geometry_class

      def build_geometry: { () -> FFI::Pointer } -> OGR::Geometry::geometry_class

      def factory: (FFI::Pointer c_pointer) -> OGR::Geometry::geometry_class

      def to_wkt: (FFI::Pointer geometry_handle) -> String
    end
  end
end
