module OGR
  class Geometry
    module SimpleCurve
      include GDAL::Logger

      def x: (Integer point_number) -> Float
      def y: (Integer point_number) -> Float

      def add_point: (ffi_floatable x, ffi_floatable y) -> void
      def point: (Integer point_number) -> [Float, Float]
      def set_point: (Integer point_number, ffi_floatable x, ffi_floatable y) -> void
      def points: -> Array[Array[Float]]
      def point_count=: (Integer new_count) -> void
      def point_count: -> Integer
    end
  end
end
