interface _AutoPointerRelease
  def release: (FFI::Pointer c_pointer) -> void
end

# TODO: Remove in favor of _HasAutoPointer
interface _HasPointer
  def c_pointer: -> FFI::Pointer
end

interface _HasAutoPointer[P]
  def c_pointer: -> P
end

interface _NewBorrowed[T]
  def new_borrowed: (FFI::Pointer c_pointer) -> T
end

interface _NewOwned[T]
  def new_owned: (FFI::Pointer c_pointer) -> T
end

interface _SpatialReference
  def spatial_reference: -> OGR::SpatialReference
  def spatial_reference=: (OGR::SpatialReference new_spatial_ref) -> void
end
