module FFI
  class AbstractMemory
    include _Size

    def []: (Integer idx) -> untyped
    def clear: -> self
    def size_limit?: -> bool
    alias total size

    def type_size: -> Integer

    def get: (Symbol | FFI::Type type_name, Integer offset) -> untyped
    def get_array_of_float32: (Integer offset, Integer length) -> Array[Float]
    def get_array_of_float64: (Integer offset, Integer length) -> Array[Float]
    def get_array_of_int16: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_int32: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_int64: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_int8: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_long: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_pointer: (Integer offset, Integer length) -> Array[FFI::Pointer]
    def get_array_of_string: (Integer offset, ?Integer count) -> Array[String]
    def get_array_of_uint16: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_uint32: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_uint64: (Integer offset, Integer length) -> Array[Integer]
    def get_array_of_uint8: (Integer offset, Integer length) -> Array[Integer]

    def get_bytes: (Integer offset, Integer length) -> String
    def get_float32: (Integer offset) -> Float
    def get_float64: (Integer offset) -> Float
    def get_int16: (Integer offset) -> Integer
    def get_int32: (Integer offset) -> Integer
    def get_int64: (Integer offset) -> Integer
    def get_int8: (Integer offset) -> Integer
    def get_long: (Integer offset) -> Integer
    def get_pointer: (Integer offset) -> FFI::Pointer
    def get_string: (Integer offset, ?Integer ?length) -> String
    def get_uint16: (Integer offset) -> Integer
    def get_uint32: (Integer offset) -> Integer
    def get_uint64: (Integer offset) -> Integer
    def get_uint8: (Integer offset) -> Integer
    def get_ulong: (Integer offset) -> Integer

    def put: (Symbol | FFI::Type type_name, Integer offset, untyped value) -> nil
    def put_array_of_float32: (Integer offset, Array[Numeric] ary) -> self
    def put_array_of_float64: (Integer offset, Array[Numeric] ary) -> self
    def put_array_of_int16: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_int32: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_int64: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_int8: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_long: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_pointer: (Integer offset, Array[FFI::Pointer] ary) -> self
    def put_array_of_uint16: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_uint32: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_uint64: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_uint8: (Integer offset, Array[Integer] ary) -> self
    def put_array_of_ulong: (Integer offset, Array[Integer] ary) -> self

    def put_bytes: (Integer offset, String str, ?Integer index, ?Integer ?length) -> self
    def put_float32: (Integer offset, Numeric value) -> self
    def put_float64: (Integer offset, Numeric value) -> self
    def put_int16: (Integer offset, Integer value) -> self
    def put_int32: (Integer offset, Integer value) -> self
    def put_int64: (Integer offset, Integer value) -> self
    def put_int8: (Integer offset, Integer value) -> self
    def put_long: (Integer offset, Integer value) -> self
    def put_pointer: (Integer offset, nil | FFI::Pointer | Integer | _ToPtr value) -> self
    def put_string: (Integer offset, String str) -> self
    def put_uint16: (Integer offset, Integer value) -> self
    def put_uint32: (Integer offset, Integer value) -> self
    def put_uint64: (Integer offset, Integer value) -> self
    def put_uint8: (Integer offset, Integer value) -> self
    def put_ulong: (Integer offset, Integer value) -> self

    def read_array_of_double: (Integer length) -> Array[Float]
    def read_array_of_float: (Integer length) -> Array[Float]
    def read_array_of_int16: (Integer length) -> Array[Integer]
    def read_array_of_int32: (Integer length) -> Array[Integer]
    def read_array_of_int64: (Integer length) -> Array[Integer]
    def read_array_of_int8: (Integer length) -> Array[Integer]
    def read_array_of_long: (Integer length) -> Array[Integer]
    def read_array_of_pointer: (Integer length) -> Array[FFI::Pointer]
    def read_array_of_uint16: (Integer length) -> Array[Integer]
    def read_array_of_uint32: (Integer length) -> Array[Integer]
    def read_array_of_uint64: (Integer length) -> Array[Integer]
    def read_array_of_uint8: (Integer length) -> Array[Integer]
    def read_array_of_ulong: (Integer length) -> Array[Integer]

    def read_bytes: (Integer length) -> String
    def read_double: () -> Float
    def read_float: () -> Float
    def read_int16: () -> Integer
    def read_int32: () -> Integer
    def read_int64: () -> Integer
    def read_int8: () -> Integer
    def read_long: () -> Integer
    def read_pointer: () -> FFI::Pointer
    def read_uint16: () -> Integer
    def read_uint32: () -> Integer
    def read_uint64: () -> Integer
    def read_uint8: () -> Integer
    def read_ulong: () -> Integer

    def write_array_of_double: (Array[Numeric] ary) -> self
    def write_array_of_float: (Array[Numeric] ary) -> self
    def write_array_of_int16: (Array[Integer] ary) -> self
    def write_array_of_int32: (Array[Integer] ary) -> self
    def write_array_of_int64: (Array[Integer] ary) -> self
    def write_array_of_int8: (Array[Integer] ary) -> self
    def write_array_of_pointer: (Array[_ToPtr] ary) -> self
    def write_array_of_uint16: (Array[Integer] ary) -> self
    def write_array_of_uint32: (Array[Integer] ary) -> self
    def write_array_of_uint64: (Array[Integer] ary) -> self
    def write_array_of_uint8: (Array[Integer] ary) -> self

    def write_bytes: (String str, ?Integer ?index, ?Integer ?length) -> self
    def write_double: (Numeric value) -> self
    def write_float: (Numeric value) -> self
    def write_int16: (Integer value) -> self
    def write_int32: (Integer value) -> self
    def write_int64: (Integer value) -> self
    def write_int8: (Integer value) -> self
    def write_pointer: (nil | FFI::Pointer | FFI::Buffer | Integer | _ToPtr value) -> self
    def write_uint16: (Integer offset) -> self
    def write_uint32: (Integer offset) -> self
    def write_uint64: (Integer offset) -> self
    def write_uint8: (Integer offset) -> self

    alias get_array_of_char       get_array_of_int8
    alias get_array_of_double     get_array_of_float64
    alias get_array_of_float      get_array_of_float32
    alias get_array_of_int        get_array_of_int32
    alias get_array_of_long_long  get_array_of_int64
    alias get_array_of_short      get_array_of_int16
    alias get_array_of_uchar      get_array_of_uint8
    alias get_array_of_uint       get_array_of_uint32
    alias get_array_of_ulong_long get_array_of_uint64
    alias get_array_of_ushort     get_array_of_uint16

    alias get_char       get_int8
    alias get_double     get_float64
    alias get_float      get_float32
    alias get_int        get_int32
    alias get_long_long  get_int64
    alias get_short      get_int16
    alias get_uchar      get_uint8
    alias get_uint       get_uint32
    alias get_ulong_long get_uint64
    alias get_ushort     get_uint16

    alias put_array_of_char       put_array_of_int8
    alias put_array_of_double     put_array_of_float64
    alias put_array_of_float      put_array_of_float32
    alias put_array_of_int        put_array_of_int32
    alias put_array_of_long_long  put_array_of_int64
    alias put_array_of_short      put_array_of_int16
    alias put_array_of_uchar      put_array_of_uint8
    alias put_array_of_uint       put_array_of_uint32
    alias put_array_of_ulong_long put_array_of_uint64
    alias put_array_of_ushort     put_array_of_uint16

    alias put_char       put_int8
    alias put_double     put_float64
    alias put_float      put_float32
    alias put_int        put_int32
    alias put_long_long  put_int64
    alias put_short      put_int16
    alias put_uchar      put_uint8
    alias put_uint       put_uint32
    alias put_ulong_long put_uint64
    alias put_ushort     put_uint16

    alias read_array_of_char       read_array_of_int8
    alias read_array_of_int        read_array_of_int32
    alias read_array_of_long_long  read_array_of_int64
    alias read_array_of_short      read_array_of_int16
    alias read_array_of_uchar      read_array_of_uint8
    alias read_array_of_uint       read_array_of_uint32
    alias read_array_of_ulong_long read_array_of_uint64
    alias read_array_of_ushort     read_array_of_uint16

    alias read_char       read_int8
    alias read_int        read_int32
    alias read_long_long  read_int64
    alias read_short      read_int16
    alias read_uchar      read_uint8
    alias read_uint       read_uint32
    alias read_ulong_long read_uint64
    alias read_ushort     read_uint16

    alias write_array_of_short     write_array_of_int16
    alias write_array_of_int       write_array_of_int32
    alias write_array_of_long_long write_array_of_int64
    alias write_array_of_char      write_array_of_int8
    alias write_short              write_int16
    alias write_int                write_int32
    alias write_long_long          write_int64
    alias write_char               write_int8
  end
end
