module FFI
  class MemoryPointer < FFI::Pointer
    def self.from_string: (String s) -> instance

    def initialize: (Integer | Symbol | FFI::Type size, ?Numeric count, ?bool clear) -> void
  end
end
