module FFI
  class Pointer < FFI::AbstractMemory
    def initialize:
      (instance pointer)                     -> void
    | (FFI::Type type_name, Integer address) -> void

    def autorelease=: (bool autorelease) -> bool
    def null?: -> bool
    def read_array_of_type: (FFI::Type ffi_type, Symbol reader_method, Numeric length) -> Array[Float]
  end
end
