module OGR
  module SpatialReferenceMixins
    module TypeChecks
      # @return [Boolean] True if the root node is a GEOGCS node.
      def geographic?: () -> untyped

      # @return [Boolean] True if the root node is a LOCAL_CS node.
      def local?: () -> untyped

      # @return [Boolean] True if it contains a PROJCS node.
      def projected?: () -> untyped

      # @return [Boolean] True if the root node is a COMPD_CS node.
      def compound?: () -> untyped

      # @return [Boolean] True if the root node is a GEOCCS node.
      def geocentric?: () -> untyped

      # @return [Boolean] True if it contains a VERT_CS node.
      def vertical?: () -> untyped

      # @param other_spatial_ref [OGR::SpatialReference, FFI::Pointer]
      # @return [Boolean] True if both SpatialReferences describe the same
      #   system.
      def same?: (untyped other_spatial_ref) -> untyped

      # @param other_spatial_ref [OGR::SpatialReference, FFI::Pointer]
      # @return [Boolean] True if the GEOGCS nodes of each SpatialReference
      #   match.
      def geog_cs_is_same?: (untyped other_spatial_ref) -> untyped

      # @param other_spatial_ref [OGR::SpatialReference, FFI::Pointer]
      # @return [Boolean] True if the VERT_CS nodes of each SpatialReference
      #   match.
      def vert_cs_is_same?: (untyped other_spatial_ref) -> untyped
    end
  end
end
