module FFI
  module OGR
    module API
      extend FFI::Library

      ValidationFlag: FFI::Enum

      type ogr_feature_h = FFI::Pointer

      type validation_flag_symbol = (
        :OGR_F_VAL_NULL
        | :OGR_F_VAL_GEOM_TYPE
        | :OGR_F_VAL_WIDTH
        | :OGR_F_VAL_ALLOW_NULL_WHEN_DEFAULT
        | :OGR_F_VAL_ALLOW_DIFFERENT_GEOM_DIM
        | :OGR_F_VAL_ALL
      )

      def self.OGR_F_Create: (FFI::OGR::API::ogr_feature_defn_h feature_definition_ptr) -> ogr_feature_h
      def self.OGR_F_Destroy: (ogr_feature_h c_pointer) -> void
      def self.OGR_F_Clone: (ogr_feature_h c_pointer) -> ogr_feature_h
      def self.OGR_F_Validate: (ogr_feature_h c_pointer, Integer flags, bool emit_error) -> bool
      def self.OGR_F_DumpReadable: (ogr_feature_h c_pointer, FFI::Pointer out_ptr) -> void

      def self.OGR_F_SetFrom: (ogr_feature_h c_pointer, ogr_feature_h other_pointer, bool forgiving) -> FFI::OGR::Core::ogr_err_symbol
      def self.OGR_F_SetFromWithMap: (
        ogr_feature_h c_pointer,
        ogr_feature_h other_pointer,
        bool forgiving,
        FFI::MemoryPointer map
      ) -> FFI::OGR::Core::ogr_err_symbol
      def self.OGR_F_GetFieldCount: (ogr_feature_h c_pointer) -> Integer

      def self.OGR_F_SetFieldNull: (ogr_feature_h c_pointer, Integer field_index) -> void
      def self.OGR_F_SetFieldString: (ogr_feature_h c_pointer, Integer field_index, String value) -> void
      def self.OGR_F_SetFieldInteger: (ogr_feature_h c_pointer, Integer field_index, Integer value) -> void
      def self.OGR_F_SetFieldInteger64: (ogr_feature_h c_pointer, Integer field_index, Integer value) -> void
      def self.OGR_F_SetFieldDouble: (ogr_feature_h c_pointer, Integer field_index, Float value) -> void
      def self.OGR_F_SetFieldStringList: (ogr_feature_h c_pointer, Integer field_index, FFI::MemoryPointer values) -> void
      def self.OGR_F_SetFieldIntegerList: (
          ogr_feature_h c_pointer,
          Integer field_index,
          Integer value_count,
          FFI::MemoryPointer values
      ) -> void
      def self.OGR_F_SetFieldInteger64List: (
          ogr_feature_h c_pointer,
          Integer field_index,
          Integer value_count,
          FFI::MemoryPointer values
      ) -> void
      def self.OGR_F_SetFieldDoubleList: (
        ogr_feature_h c_pointer,
        Integer field_index,
        Integer value_count,
        FFI::MemoryPointer values
      ) -> void

      def self.OGR_F_SetFieldRaw: (ogr_feature_h c_pointer, Integer field_index, FFI::Pointer field_pointer) -> void
      def self.OGR_F_SetFieldBinary: (
        ogr_feature_h c_pointer,
        Integer field_index,
        Integer byte_count,
        FFI::MemoryPointer data
      ) -> void

      def self.OGR_F_SetFieldDateTime: (
        ogr_feature_h c_pointer,
        Integer field_index,
        Integer year,
        Integer month,
        Integer day,
        Integer hour,
        Integer minute,
        Integer second,
        Integer tz_flag
      ) -> void

      def self.OGR_F_SetFieldDateTimeEx: (
        ogr_feature_h c_pointer,
        Integer field_index,
        Integer year,
        Integer month,
        Integer day,
        Integer hour,
        Integer minute,
        Float second,
        Integer tz_flag
      ) -> void

      def self.OGR_F_GetFieldDefnRef: (ogr_feature_h c_pointer, Integer field_index) -> FFI::OGR::API::ogr_field_defn_h
      def self.OGR_F_GetFieldIndex: (ogr_feature_h c_pointer, String field_name) -> Integer
      def self.OGR_F_GetRawFieldRef: (ogr_feature_h c_pointer, Integer field_index) -> FFI::Pointer
      def self.OGR_F_IsFieldSet: (ogr_feature_h c_pointer, Integer field_index) -> bool
      def self.OGR_F_UnsetField: (ogr_feature_h c_pointer, Integer field_index) -> void
      def self.OGR_F_GetDefnRef: (ogr_feature_h c_pointer) -> FFI::OGR::API::ogr_feature_defn_h
      def self.OGR_F_GetGeometryRef: (ogr_feature_h c_pointer) -> FFI::OGR::API::ogr_geometry_h
      def self.OGR_F_SetGeometry: (ogr_feature_h c_pointer, FFI::OGR::API::ogr_geometry_h geometry_ptr) -> (:OGRERR_NONE | :OGRERR_UNSUPPORTED_GEOMETRY_TYPE)
      def self.OGR_F_StealGeometry: (ogr_feature_h c_pointer) -> FFI::OGR::API::ogr_geometry_h
      def self.OGR_F_GetFID: (ogr_feature_h c_pointer) -> Integer
      def self.OGR_F_SetFID: (ogr_feature_h c_pointer, Integer new_feature_identifier) -> FFI::OGR::Core::ogr_err_symbol
      def self.OGR_F_GetGeomFieldCount: (ogr_feature_h c_pointer) -> Integer
      def self.OGR_F_GetGeomFieldDefnRef: (ogr_feature_h c_pointer, Integer geometry_field_index) -> FFI::OGR::API::ogr_geom_field_defn_h
      def self.OGR_F_GetGeomFieldIndex: (ogr_feature_h c_pointer, String geometry_field_name) -> Integer
      def self.OGR_F_GetGeomFieldRef: (ogr_feature_h c_pointer, Integer geometry_field_index) -> FFI::OGR::API::ogr_geometry_h
      def self.OGR_F_SetGeomField: (ogr_feature_h c_pointer, Integer geometry_field_index, FFI::OGR::API::ogr_geometry_h geometry_ptr) -> void
      def self.OGR_F_Equal: (ogr_feature_h c_pointer, ogr_feature_h other_pointer) -> bool

      def self.OGR_F_GetFieldAsInteger: (ogr_feature_h c_pointer, Integer field_index) -> Integer
      def self.OGR_F_GetFieldAsInteger64: (ogr_feature_h c_pointer, Integer field_index) -> Integer
      def self.OGR_F_GetFieldAsIntegerList: (ogr_feature_h c_pointer, Integer field_index, FFI::MemoryPointer count_in_list) -> FFI::Pointer
      def self.OGR_F_GetFieldAsInteger64List: (ogr_feature_h c_pointer, Integer field_index, FFI::MemoryPointer count_in_list) -> FFI::Pointer

      def self.OGR_F_GetFieldAsDouble: (ogr_feature_h c_pointer, Integer field_index) -> Float
      def self.OGR_F_GetFieldAsDoubleList: (ogr_feature_h c_pointer, Integer field_index, FFI::MemoryPointer count_in_list) -> FFI::Pointer

      def self.OGR_F_GetFieldAsString: (ogr_feature_h c_pointer, Integer field_index) -> String
      def self.OGR_F_GetFieldAsStringList: (ogr_feature_h c_pointer, Integer field_index) -> FFI::Pointer
      def self.OGR_F_GetFieldAsBinary: (ogr_feature_h c_pointer, Integer field_index, FFI::MemoryPointer byte_count) -> FFI::Pointer
      def self.OGR_F_GetFieldAsDateTime: (
        ogr_feature_h c_pointer,
        Integer field_index,
        FFI::MemoryPointer year,
        FFI::MemoryPointer month,
        FFI::MemoryPointer day,
        FFI::MemoryPointer hour,
        FFI::MemoryPointer minute,
        FFI::MemoryPointer second,
        FFI::MemoryPointer tz_flag
      ) -> bool

      def self.OGR_F_GetStyleString: (ogr_feature_h c_pointer) -> String
      def self.OGR_F_SetStyleString: (ogr_feature_h c_pointer, String style_string) -> void
      def self.OGR_F_GetStyleTable: (ogr_feature_h c_pointer) -> FFI::OGR::API::ogr_style_table_h
      def self.OGR_F_SetStyleTable: (ogr_feature_h c_pointer, FFI::OGR::API::ogr_style_table_h style_table_ptr) -> void
      def self.OGR_F_GetNativeData: (ogr_feature_h c_pointer) -> String
      def self.OGR_F_SetNativeData: (ogr_feature_h c_pointer, String data) -> void
      def self.OGR_F_GetNativeMediaType: (ogr_feature_h c_pointer) -> String
      def self.OGR_F_SetNativeMediaType: (ogr_feature_h c_pointer, String data) -> void
      def self.OGR_F_FillUnsetWithDefault: (ogr_feature_h c_pointer, bool not_nullable_only, FFI::Pointer options) -> void

      def self.OGR_F_IsFieldNull: (ogr_feature_h c_pointer, Integer field_index) -> bool
      def self.OGR_F_IsFieldSetAndNotNull: (ogr_feature_h c_pointer, Integer field_index) -> bool
    end
  end
end
