module FFI
  module OGR
    module API
      extend FFI::Library

      type ogr_feature_defn_h = FFI::Pointer

      def self.OGR_FD_Release: (ogr_feature_defn_h pointer) -> void
      def self.OGR_FD_Create: (String name) -> ogr_feature_defn_h
      def self.OGR_FD_IsSame: (ogr_feature_defn_h lhs, ogr_feature_defn_h rhs) -> bool
      def self.OGR_FD_GetName: (ogr_feature_defn_h c_pointer) -> String

      def self.OGR_FD_IsStyleIgnored: (ogr_feature_defn_h c_pointer) -> bool
      def self.OGR_FD_SetStyleIgnored: (ogr_feature_defn_h c_pointer, bool ignore) -> void

      def self.OGR_FD_GetFieldCount: (ogr_feature_defn_h c_pointer) -> Integer
      def self.OGR_FD_GetFieldIndex: (ogr_feature_defn_h c_pointer, String field_name) -> Integer
      def self.OGR_FD_GetFieldDefn: (ogr_feature_defn_h c_pointer, Integer index) -> FFI::OGR::API::ogr_field_defn_h
      def self.OGR_FD_AddFieldDefn: (ogr_feature_defn_h c_pointer, FFI::OGR::API::ogr_field_defn_h field_definition_ptr) -> void
      def self.OGR_FD_DeleteFieldDefn: (ogr_feature_defn_h c_pointer, Integer index) -> FFI::OGR::Core::ogr_err_symbol

      def self.OGR_FD_GetGeomType: (ogr_feature_defn_h c_pointer) -> FFI::OGR::Core::wkb_geometry_type_symbol
      def self.OGR_FD_SetGeomType: (ogr_feature_defn_h c_pointer, FFI::OGR::Core::wkb_geometry_type_symbol new_geometry_type) -> void

      def self.OGR_FD_IsGeometryIgnored: (ogr_feature_defn_h c_pointer) -> bool
      def self.OGR_FD_SetGeometryIgnored: (ogr_feature_defn_h c_pointer, bool ignore) -> void

      def self.OGR_FD_GetGeomFieldCount: (ogr_feature_defn_h c_pointer) -> Integer
      def self.OGR_FD_GetGeomFieldDefn: (ogr_feature_defn_h c_pointer, Integer index) -> FFI::OGR::API::ogr_geom_field_defn_h
      def self.OGR_FD_GetGeomFieldIndex: (ogr_feature_defn_h c_pointer, String geometry_field_name) -> Integer
      def self.OGR_FD_AddGeomFieldDefn: (ogr_feature_defn_h c_pointer, FFI::OGR::API::ogr_geom_field_defn_h geometry_field_definition_ptr) -> void
      def self.OGR_FD_DeleteGeomFieldDefn: (ogr_feature_defn_h c_pointer, Integer index) -> FFI::OGR::Core::ogr_err_symbol
    end
  end
end
