module FFI
  module OGR
    module API
      extend FFI::Library

      def self.OGR_Fld_Create: (String field_name, FFI::OGR::Core::ogr_field_type_symbol field_type) -> FFI::Pointer
      def self.OGR_Fld_Destroy: (FFI::Pointer field_def_pointer) -> void
      def self.OGR_Fld_SetName: (FFI::Pointer field_def_pointer, String new_name) -> void
      def self.OGR_Fld_GetNameRef: (FFI::Pointer field_def_pointer) -> String
      def self.OGR_Fld_GetType: (FFI::Pointer field_def_pointer) -> FFI::OGR::Core::ogr_field_type_symbol
      def self.OGR_Fld_SetType: (FFI::Pointer field_def_pointer, FFI::OGR::Core::ogr_field_type_symbol field_type) -> void
      def self.OGR_Fld_GetJustify: (FFI::Pointer field_def_pointer) -> FFI::OGR::Core::ogr_justification_symbol
      def self.OGR_Fld_SetJustify: (FFI::Pointer field_def_pointer, FFI::OGR::Core::ogr_justification_symbol justification) -> void
      def self.OGR_Fld_GetWidth: (FFI::Pointer field_def_pointer) -> Integer
      def self.OGR_Fld_SetWidth: (FFI::Pointer field_def_pointer, Integer width) -> void
      def self.OGR_Fld_GetPrecision: (FFI::Pointer field_def_pointer) -> Integer
      def self.OGR_Fld_SetPrecision: (FFI::Pointer field_def_pointer, Integer precision) -> void
      def self.OGR_Fld_IsIgnored: (FFI::Pointer field_def_pointer) -> bool
      def self.OGR_Fld_SetIgnored: (FFI::Pointer field_def_pointer, bool ignore) -> void
      def self.OGR_Fld_GetSubType: (FFI::Pointer field_def_pointer) -> FFI::OGR::Core::ogr_field_sub_type_symbol
      def self.OGR_Fld_SetSubType: (FFI::Pointer field_def_pointer, FFI::OGR::Core::ogr_field_sub_type_symbol) -> void
      def self.OGR_Fld_IsNullable: (FFI::Pointer field_def_pointer) -> bool
      def self.OGR_Fld_SetNullable: (FFI::Pointer field_def_pointer, bool is_nullable) -> void

      def self.OGR_Fld_Set: (
          FFI::Pointer field_def_pointer,
          String field_name,
          FFI::OGR::Core::ogr_field_type_symbol field_type,
          Integer ?width,
          Integer ?precision,
          FFI::OGR::Core::ogr_justification_symbol ?justification
      ) -> void
    end
  end
end
