module OGR
  class MultiLineString
    include OGR::Geometry

    include GeometryTypes::Curve

    include GeometryTypes::Container

    # @param [FFI::Pointer] geometry_ptr
    def initialize: (?untyped? geometry_ptr, ?spatial_reference: untyped? spatial_reference) -> untyped
  end
end
