module OGR
  # NOTE: {{#type}} will return :wkbPolygon (read: 2D instead of 2.5D) until a Z
  # value is set.
  class Polygon25D < Polygon
    # @param geometry_ptr [FFI::Pointer]
    # @param spatial_reference [OGR::SpatialReference]
    def initialize: (?untyped? geometry_ptr, ?spatial_reference: untyped? spatial_reference) -> untyped
  end
end
